### ISSUE TITLE
Crashing when dragging a cell from one section to another section

### ISSUE THREAD

**Issue by rhkrthdud7** [sivu22/LongPressReorder#1]
Hello,
I am currently using your LongPressReorder but I am having issues when dragging a cell from one section to another one. Is this only working for one section table only? Or is this only working for static tableView cells? Let me know if I am using it the wrong way.
I just crashes and I wasn't able to see why it crashed. Thank you.

**Comment by sivu22** [comment]
Your intuition is correct, it works only for a one section table only (but with dynamic cells). The protocol only delivers indexes inside the table but no section information.

I have changed the readme to include this information. Sorry for the trouble.
