### ISSUE TITLE
LongPressReorder and cell height

### ISSUE THREAD

**Issue by mezhevikin** [sivu22/LongPressReorder#2]
Hello @sivu22
Thank you for this repository.

Tell me please, how to use LongPressReorder if i have cells with different height?

Demo - https://www.youtube.com/watch?v=QA4KL4FFWWQ&feature=youtu.be

**Comment by sivu22** [comment]
Glad you like it.

Are you computing the cell height dynamically?

Assuming you are determining the cell height inside `tableView:heightForRowAtIndexPath:` based on your model, you should override the protocol function that notifies you when 2 cells switch places:
`override func positionChanged(currentIndex: IndexPath, newIndex: IndexPath) {
     // Update model by swapping currentIndex with newIndex
     }`

If you update the model accordingly inside this notification function, the next time `tableView:heightForRowAtIndexPath:` will be called, the cells will have the correct heights returned.
