### ISSUE TITLE
whne drag row the scroll of tableview doen't work

### ISSUE THREAD

**Issue by Spiderbezno** [sivu22/LongPressReorder#3]
I 'm dragging a row and arrive to end of visible tableview but the scroll of tableview doesn't work, is there any option to enable the scroll of tableview during drag roe??

**Comment by sivu22** [comment]
Unfortunately not. I will implement it though on the next occasion.

**Comment by Spiderbezno** [comment]
Some tip on how can implement that?

**Comment by sivu22** [comment]
First thought is to check where the dragged cell is located relative to the TableView and then scroll the TableView one cell at a time until the first (or last) cell is reached. But I would need to prototype this to be sure it is a valid solution.

**Comment by sivu22** [comment]
Autoscroll was implemented in version 1.2.0.
