### ISSUE TITLE
Dismiss keyboard when re-order begins?

### ISSUE THREAD

**Issue by ashzade** [sivu22/LongPressReorder#4]
This is a great pod. The only challenge I have is that when reorder begins, I want to dismiss a keyboard if it's open. I already have the keyboard dismissing if there is a tap but it doesn't seem to fire for this. Any ideas?

**Comment by sivu22** [comment]
Glad you like it.

Have you tried dismissing the keyboard inside the `startReorderingRow(atIndex:)` callback? Just override it inside your VC and decide there what to do about the keyboard.

**Comment by ashzade** [comment]
That did it! Thanks again. If you're interested, this is the app: www.outlinenotes.com. Your work is a huge part of it.

**Comment by sivu22** [comment]
Nice app, congratulations!
