### ISSUE TITLE
Move more than one row at a time?

### ISSUE THREAD

**Issue by ashzade** [sivu22/LongPressReorder#6]
I have a tree structure so rows may have children. I can't figure out how to move them when the parent is moved. Any ideas for this?

**Comment by sivu22** [comment]
Are you talking about a nested UITableView? Are the children also rows or table views?
I would try to collapse everything under the cell, and only then reorder it in the main table.

**Comment by ashzade** [comment]
Sorry, I should have included more detail. The children are rows and the parent-child relationship is in the datasource.

**Comment by sivu22** [comment]
I see. I still believe you should implement expand/collapse on the parent rows and do the reordering at the parent level, when all children are hidden. Not only would this make things easier, but it also looks better in my opinion.
