### ISSUE TITLE
Can't drag the last 4 or 5 rows

### ISSUE THREAD

**Issue by ashzade** [sivu22/LongPressReorder#7]
Hi,

I can't tell if this is an issue in my code or part of a problem in iOS 12. I can't drag the last few rows in my UITableView. You can see that I can drag rows to the bottom but can't drag things from there. Any idea? https://i.imgur.com/7HDgB39.gifv

EDIT: Solved! There was a UIView at the bottom right of my view: https://imgur.com/a/Ec0MK8G

**Comment by sivu22** [comment]
Strange, haven't encountered such a situation. I assume you have some rows that can't be moved - check for the startReorderingRow(atIndex:) and allowChangingRow(atIndex:) functions. Another idea is some error in the model (especially after reordering some rows) or in the table delegates, like numberOfRowsInSection, cellForRowAt, ...

In any case, I would put debug logs in my TableView/Controller implementation of the LongPressReorder protocol and check for correctness.

**Comment by sivu22** [comment]
@ashzade found the issue?
