### ISSUE TITLE
Core Data implementation

### ISSUE THREAD

**Issue by nurlan-dzhavadov** [sivu22/LongPressReorder#9]
Hello!
Thank you for this library! My question is: does the function in this library:
override func reorderFinished(initialIndex: IndexPath, finalIndex: IndexPath) {
        
    }
replace this one:
override func tableView(tableView: UITableView, moveRowAtIndexPath fromIndexPath: NSIndexPath, toIndexPath: NSIndexPath) {

}

??? The problem is that I want to save the result of reordering in Core Data, however there are only solutions for the first function and all these answers don't work at all!
I'm stuck and don't know what to do. I'm new to iOS development. Maybe you know how to solve this problem. That would help me a lot.
Thank you!

**Comment by sivu22** [comment]
Hi,

they are similar so to say, meaning they are both used for updating the data source when rows change. But don't mix them. If you are using LongPressReorder, update your model via the reorderFinished callback. 

Maybe the Core Data issue is not related to reordering? Try to save something outside reordering and take it from there.

**Comment by nurlan-dzhavadov** [comment]
Thank you a lot!
